fix: set minimum free-proxy version
scholarly requires free-proxy >= 1.1.0, see
```
  File "/.../scholarly/_proxy_generator.py", line 509, in _fp_coroutine
    all_proxies = freeproxy.get_proxy_list(repeat=False)  # free-proxy >= 1.1.0
TypeError: get_proxy_list() got an unexpected keyword argument 'repeat'
```